#!/usr/bin/env bash
# =============================================================================
# Quilin Agent — 自动发布脚本
# =============================================================================
# 自动 commit + 打 tag + push
#
# 用法：
#   bash scripts/release.sh                  # 自动 patch 版本
#   bash scripts/release.sh --minor          # minor 版本
#   bash scripts/release.sh --major          # major 版本
#   bash scripts/release.sh --version 1.2.3  # 指定版本
#   bash scripts/release.sh --dry-run        # 只预览，不执行
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"

# 默认值
BUMP_TYPE="patch"
CUSTOM_VERSION=""
DRY_RUN=false
PUSH_REMOTE=true

# 解析参数
while [[ $# -gt 0 ]]; do
    case $1 in
        --major)    BUMP_TYPE="major"; shift ;;
        --minor)    BUMP_TYPE="minor"; shift ;;
        --patch)    BUMP_TYPE="patch"; shift ;;
        --version)  CUSTOM_VERSION="$2"; shift 2 ;;
        --dry-run)  DRY_RUN=true; shift ;;
        --no-push)  PUSH_REMOTE=false; shift ;;
        *)          echo "Unknown option: $1"; exit 1 ;;
    esac
done

cd "$ROOT_DIR"

log() {
    echo "[release] $*"
}

# =============================================================================
# Step 1: 检查工作区状态
# =============================================================================
log "Checking working directory..."

if ! git diff --quiet 2>/dev/null || ! git diff --cached --quiet 2>/dev/null; then
    CHANGES=true
else
    CHANGES=false
fi

UNTRACKED=$(git ls-files --others --exclude-standard | head -20)

if [[ "$CHANGES" == "false" ]] && [[ -z "$UNTRACKED" ]]; then
    log "No changes to release"
    exit 0
fi

log "Changes detected, proceeding with release..."

# =============================================================================
# Step 2: 获取当前版本并计算新版本
# =============================================================================
log "Calculating version..."

# 从 git tag 获取最新版本
LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
CURRENT_VERSION="${LATEST_TAG#v}"

if [[ -n "$CUSTOM_VERSION" ]]; then
    NEW_VERSION="$CUSTOM_VERSION"
else
    IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT_VERSION"
    MAJOR=${MAJOR:-0}
    MINOR=${MINOR:-0}
    PATCH=${PATCH:-0}

    case "$BUMP_TYPE" in
        major) NEW_VERSION="$((MAJOR + 1)).0.0" ;;
        minor) NEW_VERSION="$MAJOR.$((MINOR + 1)).0" ;;
        patch) NEW_VERSION="$MAJOR.$MINOR.$((PATCH + 1))" ;;
    esac
fi

NEW_TAG="v$NEW_VERSION"
log "Version: $CURRENT_VERSION -> $NEW_VERSION ($NEW_TAG)"

if $DRY_RUN; then
    log "[DRY RUN] Would commit, tag $NEW_TAG, and push"
    git status --short
    exit 0
fi

# =============================================================================
# Step 3: 生成变更摘要
# =============================================================================
log "Generating changelog..."

# 收集自上次 tag 以来的 submodule 更新
SUBMODULE_CHANGES=""
if [[ "$LATEST_TAG" != "v0.0.0" ]]; then
    SUBMODULE_CHANGES=$(git diff "$LATEST_TAG"..HEAD --submodule=short 2>/dev/null || echo "")
fi

# 收集 quilin 核心代码变更
CORE_CHANGES=$(git diff "$LATEST_TAG"..HEAD --stat -- quilin/ 2>/dev/null || echo "Initial release")

# =============================================================================
# Step 4: Stage + Commit
# =============================================================================
log "Staging changes..."

# 更新 submodule 引用
git add -A upstreams/ 2>/dev/null || true

# 添加核心代码变更
git add -A quilin/ scripts/ 2>/dev/null || true

# 添加配置文件
git add -A *.yaml *.yml *.toml Dockerfile .gitmodules 2>/dev/null || true

# 生成 commit message
COMMIT_MSG="release: $NEW_TAG

Upstream updates:
${SUBMODULE_CHANGES:-  (none)}

Core changes:
${CORE_CHANGES:-  (initial release)}

Auto-generated by Quilin Agent release.sh"

log "Committing..."
git commit -m "$COMMIT_MSG" || {
    log "Nothing to commit"
    exit 0
}

# =============================================================================
# Step 5: 打 Tag
# =============================================================================
log "Tagging $NEW_TAG..."

TAG_MSG="Quilin Agent $NEW_TAG

Released: $(date -u '+%Y-%m-%d %H:%M:%S UTC')
Changes since $LATEST_TAG:
$(git log "$LATEST_TAG"..HEAD --oneline 2>/dev/null || echo "  Initial release")"

git tag -a "$NEW_TAG" -m "$TAG_MSG"

# =============================================================================
# Step 6: Push
# =============================================================================
if $PUSH_REMOTE; then
    log "Pushing to remote..."

    # 检查是否有 remote
    if git remote get-url origin &>/dev/null; then
        git push origin HEAD
        git push origin "$NEW_TAG"
        log "Pushed $NEW_TAG to origin"
    else
        log "WARN: No remote 'origin' configured, skipping push"
        log "Run: git remote add origin <url> && git push -u origin main --tags"
    fi
else
    log "Skipping push (--no-push)"
fi

# =============================================================================
# 完成
# =============================================================================
log ""
log "=========================================="
log " Release $NEW_TAG complete!"
log "=========================================="
log " Tag:    $NEW_TAG"
log " Commit: $(git rev-parse --short HEAD)"
log " Date:   $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
log "=========================================="
